In [1]:
import duckdb
import pandas as pd
from pathlib import Path

In [2]:
db_path = Path(f'{Path.cwd()}/sm_db.duckdb')
print(f"cwd: {Path.cwd()} \n filepaht: {db_path}")
db_path.exists()
conn = duckdb.connect(db_path, read_only=True)
stroke_mortality_clean = conn.sql("SELECT  * FROM stroke_mortality;").df()

cwd: c:\Data_Analysis_Projects\HHS_data_analysis\analysis\stroke_mortality_analysis
 filepaht: c:\Data_Analysis_Projects\HHS_data_analysis\analysis\stroke_mortality_analysis\sm_db.duckdb

In [3]:
stroke_mortality_clean.head()

,id,api_id,year,state,location,geo_level,rate,sex,race,fips,icd_class,value,topic
0,1490899,row-9mxu_6uqv-j4kv,2004,IL,Schuyler,County,"per 100,000",Women,Overall,17169,Cardiovascular Diseases,41.0,Coronary heart disease (CHD)
1,1490900,row-rgch~giks_tdv8,2017,IL,Schuyler,County,"per 100,000",Women,Overall,17169,Cardiovascular Diseases,39.4,Coronary heart disease (CHD)
2,1490901,row-asyv_kbrc-barf,1999,IL,Schuyler,County,"per 100,000",Women,Overall,17169,Cardiovascular Diseases,52.6,Coronary heart disease (CHD)
3,1490902,row-6scm_2i8j.jaqv,2019,IL,Schuyler,County,"per 100,000",Women,Overall,17169,Cardiovascular Diseases,38.0,Coronary heart disease (CHD)
4,1490903,row-dx4n~f74v_k85s,2018,IL,Schuyler,County,"per 100,000",Women,Overall,17169,Cardiovascular Diseases,40.7,Coronary heart disease (CHD)

In [4]:
stroke_mortality_clean['sex'] = stroke_mortality_clean['sex'].replace('Men', 'Male')
stroke_mortality_clean['sex'] = stroke_mortality_clean['sex'].replace('Women', 'Female')
stroke_mortality_clean['race'] = stroke_mortality_clean['race'].replace('American Indian or Alaska Native', 'American Indian/Alaska Native')
stroke_mortality_clean['race'] = stroke_mortality_clean['race'].replace('Black', 'Black (Non-Hispanic)')
stroke_mortality_clean['race'] = stroke_mortality_clean['race'].replace('Asian', 'Asian/Pacific Islander')
stroke_mortality_clean['race'] = stroke_mortality_clean['race'].replace('Native Hawaiian or Other Pacific Islander', 'Asian/Pacific Islander')

In [5]:
stroke_mortality_clean['race'].unique()

<StringArray>
[                      'Overall',                         'White',
          'Black (Non-Hispanic)',                      'Hispanic',
        'Asian/Pacific Islander', 'American Indian/Alaska Native',
            'More than one race']
Length: 7, dtype: str

In [6]:
stroke_mortality_clean['sex'].unique()

<StringArray>
['Female', 'Overall', 'Male']
Length: 3, dtype: str

In [7]:
stroke_mortality_clean['location'] = stroke_mortality_clean['location'].str.replace('County', '' ,regex=False).str.strip()

In [8]:
stroke_mortality_clean['location'].unique()

<StringArray>
[     'Schuyler',        'Shelby',         'Piatt',     'Vermilion',
     'Anchorage',         'White',          'Pike',      'Randolph',
        'Wabash',         'Iosco',
 ...
 'West Virginia',    'Sweetwater',         'Uinta',      'Washakie',
        'Weston',   'Puerto Rico',       'Newport',    'Providence',
  'Rhode Island',  'South Dakota']
Length: 2061, dtype: str

In [9]:
stroke_mortality_clean.count()

id           5417584
api_id       5417584
year         5417584
state        5417584
location     5417584
geo_level    5417584
rate         5417584
sex          5417584
race         5417584
fips         5417584
icd_class    5417584
value        3162919
topic        5407824
dtype: int64

In [10]:
stroke_mortality_clean = stroke_mortality_clean.dropna()

In [11]:
stroke_mortality_clean.count()

id           3157962
api_id       3157962
year         3157962
state        3157962
location     3157962
geo_level    3157962
rate         3157962
sex          3157962
race         3157962
fips         3157962
icd_class    3157962
value        3157962
topic        3157962
dtype: int64

In [12]:
stroke_mortality_clean.head()

,id,api_id,year,state,location,geo_level,rate,sex,race,fips,icd_class,value,topic
0,1490899,row-9mxu_6uqv-j4kv,2004,IL,Schuyler,County,"per 100,000",Female,Overall,17169,Cardiovascular Diseases,41.0,Coronary heart disease (CHD)
1,1490900,row-rgch~giks_tdv8,2017,IL,Schuyler,County,"per 100,000",Female,Overall,17169,Cardiovascular Diseases,39.4,Coronary heart disease (CHD)
2,1490901,row-asyv_kbrc-barf,1999,IL,Schuyler,County,"per 100,000",Female,Overall,17169,Cardiovascular Diseases,52.6,Coronary heart disease (CHD)
3,1490902,row-6scm_2i8j.jaqv,2019,IL,Schuyler,County,"per 100,000",Female,Overall,17169,Cardiovascular Diseases,38.0,Coronary heart disease (CHD)
4,1490903,row-dx4n~f74v_k85s,2018,IL,Schuyler,County,"per 100,000",Female,Overall,17169,Cardiovascular Diseases,40.7,Coronary heart disease (CHD)

In [13]:
stroke_mortality_clean.count()

id           3157962
api_id       3157962
year         3157962
state        3157962
location     3157962
geo_level    3157962
rate         3157962
sex          3157962
race         3157962
fips         3157962
icd_class    3157962
value        3157962
topic        3157962
dtype: int64

In [14]:
Nj_Stroke_Mortality = stroke_mortality_clean[
    (stroke_mortality_clean['state'] == 'NJ') &
    (stroke_mortality_clean['sex'] == 'Overall') &
    (stroke_mortality_clean['race'] == 'Overall')
].copy()

In [ ]:
Nj_Stroke_Mortality = Nj_Stroke_Mortality.sort_values('year')
Nj_Stroke_Mortality['year'] = pd.to_datetime(Nj_Stroke_Mortality['year'],format='%Y')
Nj_Stroke_Mortality = Nj_Stroke_Mortality.set_index('year')
Nj_Stroke_Mortality = Nj_Stroke_Mortality.rename(columns={'value' : 'rate'})

In [16]:
Nj_Stroke_Mortality.head()

,id,api_id,state,location,geo_level,rate,sex,race,fips,icd_class,value,topic
year,,,,,,,,,,,,
1999-01-01,3355556,row-mzx5~rpx2-ysw3,NJ,Passaic,County,"per 100,000",Overall,Overall,34031,Cardiovascular Diseases,112.4,All heart disease
1999-01-01,3331756,row-pvg7_jby3_kvdz,NJ,Camden,County,"per 100,000",Overall,Overall,34007,Cardiovascular Diseases,121.5,All heart disease
1999-01-01,3360441,row-rmgv-2wbi-ad28,NJ,Somerset,County,"per 100,000",Overall,Overall,34035,Cardiovascular Diseases,10.9,All stroke
1999-01-01,3357236,row-j78n-429m_edgw,NJ,Salem,County,"per 100,000",Overall,Overall,34033,Cardiovascular Diseases,147.5,All heart disease
1999-01-01,3344692,row-m2nt.s3ff_txt2,NJ,Hudson,County,"per 100,000",Overall,Overall,34017,Cardiovascular Diseases,2469.7,Cardiovascular disease (CVD)

In [17]:
Nj_Stroke_Mortality.count()

id           4454
api_id       4454
state        4454
location     4454
geo_level    4454
rate         4454
sex          4454
race         4454
fips         4454
icd_class    4454
value        4454
topic        4454
dtype: int64